version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: Install npm dependencies
        command: npm install
    - run:
        name: Run Linting
        command: npm run lint
    - run:
        name: Run Unit Tests
        command: npm test
    
workflows:
  build_test:
    jobs:
      - run_tests
